[package]
name = "three-way-merge"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.34"
colog = "1.3.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
